development:
  adapter: postgresql
  encoding: unicode
  database: tagsurf_development
  username:
  password:
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: tagsurf_development
  username:
  password:
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: tagsurf_test
  username:
  password:
  host: localhost
  port: 5432

